name: Clean HTML
on:
  workflow_dispatch:
jobs:
  clean:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Run cleanup script
        run: python3 clean.py
      - name: Commit
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add index.html
          git commit -m "Remove base64 images and Charizard article" || echo "No changes"
          git push